#include "flexaid.h"
#include "boinc.h"

/******************************************************************************
 * SUBROUTINE write_pdb writes a PDB file
 ******************************************************************************/
int write_pdb(FA_Global* FA,atom *atoms, resid* residue,char outfile[], char remark[]){
    int  i,j,k;
    char field[7];
    int rot;
    FILE *outfile_ptr;
    
    outfile_ptr=NULL;
    if(!OpenFile_B(outfile,"w",&outfile_ptr)){
        Terminate(6);
    }else{
        
        // write header information
        fprintf(outfile_ptr,"HEADER coordinate file generated by FlexAID\n");
        fprintf(outfile_ptr,"%s\n",remark);
        
        for(k=1;k<=FA->res_cnt;k++){
            rot=residue[k].rot;
            
            /*
             printf("write_pdb: rot is %d - fatm: %d - latm: %d - atoms[%d].number = %d\n",rot,residue[k].fatm[rot],residue[k].latm[rot],
             residue[k].fatm[rot],atoms[residue[k].fatm[rot]].number);
             */
            
            for(i=residue[k].fatm[rot];i<=residue[k].latm[rot];i++){
                
                if(!FA->output_scored_only || atoms[i].optres != NULL){
                    
                    if(residue[atoms[i].ofres].type==0){strcpy(field,"ATOM  ");}
                    if(residue[atoms[i].ofres].type==1){strcpy(field,"HETATM");}
                    
                    fprintf(outfile_ptr,"%s%5d %s %s %c%4d    %8.3f%8.3f%8.3f  1.00  0.00\n",
                            field,
                            atoms[i].number,
                            atoms[i].name,
                            residue[atoms[i].ofres].name,
                            residue[atoms[i].ofres].chn,
                            residue[atoms[i].ofres].number,
                            atoms[i].coor[0],
                            atoms[i].coor[1],
                            atoms[i].coor[2]
                            );
                    
                }
            }
        }
        
        //view the protein center geometry
        //fprintf(outfile_ptr, "HETATM99999  C   ORI -9999    %8.3f%8.3f%8.3f  1.00  0.00\n",
        //	    FA->ori[0],FA->ori[1],FA->ori[2]);
        
        // write conect data for all ligands
        for(i=1;i<=FA->num_het;i++){
            rot=residue[FA->het_res[i]].rot;
            
            for(j=residue[FA->het_res[i]].fatm[rot];j<=residue[FA->het_res[i]].latm[rot];j++){
                
                fprintf(outfile_ptr,"CONECT%5d",atoms[j].number);
                for(k=1;k<=atoms[j].bond[0];k++){
                    fprintf(outfile_ptr,"%5d",atoms[atoms[j].bond[k]].number);
                }
                fprintf(outfile_ptr,"\n");
            }
        }
    }  
    CloseFile_B(&outfile_ptr,"w");
    
    return(0);
}
